dist: trusty
language: node_js
node_js:
    - 11
branches:
  except:
    - gh-pages
    - l10n_develop
        
addons:
  sonarcloud:
    organization: "kinbald-github"
  artifacts:
    region: "eu-west-1"
    paths:
        - ./report

before_script:
    - mkdir -p $HOME/bin
    - wget https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-4.0.2-release.zip -O $HOME/bin/dc.zip
    - wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64 -O $HOME/bin/klar
    - cd $HOME/bin/ && unzip dc.zip
    - cd -
 
script:
    - npm install
    - sudo mkdir report && sudo chown 1000:1000 report
#    - sh $HOME/bin/dependency-check/bin/dependency-check.sh --project juice-shop -s . --out report
#    - docker run -t -v $(pwd)/report:/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://54.171.133.1:32771/ -r testreport.html || true

 #   - sonar-scanner -Dsonar.projectKey=kinbald_juice-shop -Dsonar.javascript.lcov.reportPaths=./build/reports/coverage/server-tests/lcov.info
service:
    - docker
    
env:
    - IMAGE_NAME="483761293063.dkr.ecr.eu-west-1.amazonaws.com/isentest:1.0-$TRAVIS_BUILD_NUMBER"

after_success:
#  - rm -rf node_modules
#  - rm -rf frontend/node_modules
#  - npm install --production
#  - npm run package
    - pip install --user awscli
    - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
    - docker build  -t kinbald/juice-shop .   
    - docker tag kinbald/juice-shop $IMAGE_NAME
    - docker push $IMAGE_NAME
    - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ISENStackDeploy --region eu-west-1 --parameter-override ImageName=$IMAGE_NAME
    - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ISENStackDeploy --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=$IMAGE_NAME"
    - export DOCKER_LOGIN=`aws ecr get-login --no-include-email`
    - export PASSWORD=`echo $DOCKER_LOGIN | cut -d' ' -f6`
    - export REGISTRY=`echo $DOCKER_LOGIN | cut -d' ' -f7 | sed "s/https:\/\///"`
    - export DOCKER_USER=AWS DOCKER_PASSWORD=${PASSWORD} ${HOME}/bin/klar ${REGISTRY}/${IMAGE_NAME}
    - CLAIR_ADDR=http://clair.3r1.co:6060 CLAIR_OUTPUT=High CLAIR_THRESHOLD=10 DOCKER_USER=$DOCKER_USER DOCKER_PASSWORD=$PASSWORD $HOME/bin/klar postgres:9.5.1
